### ISSUE TITLE
Update your documentation

### ISSUE THREAD

**Issue by ghost** [Boorunaut/Boorunaut#140]
I mean it's really bad.
It explains nothing about setting up a Python venv server and even when I do and run the commands, I run the migrate commands and can't access the website. All I get is an apache2 website. I can't get Boorunaut to work at all.

If you don't want to then at least make an install.sh script.

**Comment by Luk3M** [comment]
I see what you mean, I'll expand the documentation. I wrote as if anyone was familiar with everything on Django.

I'll also create an install.sh script to make it easier.

Check which url is given to you when you run `python manage.py runserver`. It probably was `localhost:8000`. If it's the case, you can access this URL to see Boorunaut's index page.

**Comment by Polytelus** [comment]
About Django, the default 2.1.4 was giving me errors while creating an account, so i'd advise to bump it up to 2.1.7, it seems to have fixed the account creation problem right away. Infortunately i didn't save the entire error log, but the main one was "no such table: main.booru_post__old".
