### ISSUE TITLE
Clicking "choose file" on "media" and selecting a file does nothing.

### ISSUE THREAD

**Issue by Polytelus** [Boorunaut/Boorunaut#147]
I don't know if it's broken or anything, but trying to pull a file from my computer on the upload screen seems to do anything useful. Importing a image from the web works fine, though. I though it was just a simple bug and tried to upload anyway, but it didn't do anything either.

[https://prnt.sc/u1anx9](url)

Server OS: Ubuntu 18.04 LTS
Client OS: Windows 10 Home 2004

**Comment by Luk3M** [comment]
This might be a visual problem: it doesn't show anything, but the image entered successfully. Can test that for me? Press the button, choose an image, write a tag (and press space for confirming the tag) and send.

**Comment by Polytelus** [comment]
Hi! I tested the new changes and the thumbnail viewer you added works properly! However trying to post it gives me a "please use valid URLS" and refuses to create the post, even though it's not a image from the internet, rather it's a uploaded one.
